### ISSUE TITLE
Efficiency enchantment doesn't apply to the appropriate blocks

### ISSUE THREAD

**Issue by el-noobMC** [MelanX/vanilla-excavators#3]
Minecraft: 1.16.1
Forge: 32.0.108
morevanillalib-1.16.1-1.2.8
vanillaexcavators-1.16.1-2.1.1

Efficiency enchantment doesn't increase the mining speed when breaking blocks that are supposed to be broken with a shovel and instead increases the mining speed when breaking blocks that are supposed to be broken with a pickaxe.

**Comment by MelanX** [comment]
fixed for 1.16.2 version
