### ISSUE TITLE
so my game crashes on startup 

### ISSUE THREAD

**Issue by FrostyAnger** [MelanX/vanilla-excavators#5]
[latest.log](https://github.com/MelanX/vanilla-excavators/files/5539966/latest.log)
I'm notifying all mod devs of the mods involved in this crash

**Comment by MelanX** [comment]
Please use pastebin and provide at least any information about which versions you use. Forge, MC, Lib and Excavators

**Comment by FrostyAnger** [comment]
nvm it was the fabric mod im using forge my bad
