### ISSUE TITLE
License change

### ISSUE THREAD

**Issue by MelanX** [MelanX/vanilla-excavators#7]
I want to change to license from GPL-3.0 License to Apache 2.0 License. More information can be found here: https://www.apache.org/licenses/LICENSE-2.0.txt

Before I change it, I need permissions from all contributors of this project. All the users below, do you agree the change to Apache 2.0?
- [ ] @Aemande123 
- [x] @TheDirectorX
- [x] d3ath9un (Discord)

An the ones before I forked it:
- [x] @Draylar
- [x] @LemmaEOF
- [x] @pandory-network
- [ ] @XuyuEre

**Comment by asiekierka** [comment]
The template *should* be CC0, at least on my side.

**Comment by MelanX** [comment]
I don't know which Template was used by Draylar, so I can't check it :/

**Comment by Draylar** [comment]
Yes, it was the CC0 template, so we are good without the approval of the bottom 6. Thanks asie!

**Comment by LemmaEOF** [comment]
Go ahead! You've got my approval for both Hammers and Excavators.

**Comment by TheDirectorX** [comment]
https://github.com/MelanX/MoreVanillaTools/issues/28#issuecomment-922494947

**Comment by MelanX** [comment]
Reminder for @Aemande123 @pandory-network and @XuyuEre.
Everyone else could unsubscribe this thread in case they feel bothered.
![image](https://user-images.githubusercontent.com/26039509/158076631-e3959114-c994-4d2b-b254-5af73fba248f.png)

**Comment by kaffeekirsche** [comment]
I agree the change to Apache 2.0
